//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public System.Guid IDBitacora { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string TablaAfectada { get; set; }
        public string TipoAccion { get; set; }
        public string Detalles { get; set; }
    }
}
