//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public long IDVentas { get; set; }
        public Nullable<long> IDPedido { get; set; }
        public Nullable<long> IDProducto { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Carrito Carrito { get; set; }
    }
}
